### PR TITLE
Fix parse error when checking version

### PR DESCRIPTION
**Pull request by braunsonm**
There is no need to have jq used here. Using jq here on certain versions (2.0.4) results in a parser error.

### CODE REVIEW

**Review by mmanciop — APPROVED** [review]

**Comment by mmanciop** [comment]
@braunsonm the issue is because of the color-formatting of `jq`? Or is the problem the pretty-printing? Can you show me the error? The later case could be fixed with a `jq -c` instead of manually building JSON with `printf`.

**Review by mmanciop — APPROVED** [review]

**Comment by braunsonm** [comment]
@mmanciop are you sure it had anything to do with color? The problem seemed to be because it was trying to parse it into a decimal which won't work with all types of versions

**Comment by mmanciop** [comment]
I am not sure, I don't have anymore a ConcourseCI to repro and you did not provide the error message. I am pretty confident, however, that jq used like I did has the same effect as the print you proposed, but without introducing another way of generating json. Did the new version solve at least the version check issue?

**Comment by mmanciop** [comment]
It would help to see the values it was failing for you with :-)

**Pull request merged**
